### PR TITLE
Prepare for Release 0.0.5

### PR DESCRIPTION
**Pull request by BenWeisz**
# Description
- Add icon image for package
- Updated README

### CODE REVIEW

**Comment by BenWeisz** [comment]
@nagata-yoshiteru I've added a icon image for the vscode store (its the same as my old extension) Let me know if you have something you like better and then we can change it. I've also updated the readme with all of our features. 

I think after this is merged in we can reupload the extension. At this point, since this extension has P2, P3 support I'll remove my old extension from the store. 

It has been a pleasure working with you! I think after we upload this new release we can stop doing updates for a while unless of course someone logs an issues report. Thank you again for taking me on!

**Comment by BenWeisz** [comment]
Actually there might be a few other features that I would like to add 😅, but we can probably work on these later:
- [ ] Showing the pixel data in the zoom panel for the pixel your mouse is over
- [ ] Auto refresh viewer when file has changes

**Comment by nagata-yoshiteru** [comment]
Hello, @BenWeisz!
Thank you for preparing release v0.0.5. I think the icon is excellent and suitable for our extension!

I added a minor update in `README.md`, `CHANGELOG.md`, and `package.json`. So I think we are ready to release v0.0.5! If there is no problem, I will release the update to the store.

After releasing v0.0.5, I also think we can stop doing updates. However, there are also some features I want to add in the future:

- [ ] Zoom in and out with `Ctrl` key + mouse scroll
- [ ] Performance improvement for large images 
- [ ] Support more wide variety of image formats

I have been very exciting to work with you! It's my first time collaborating with others on GitHub, but you are very kind and helpful! So I could work with you very easily. Thank you for collaborating with me!

**Review by nagata-yoshiteru — APPROVED** [review]

**Comment by BenWeisz** [comment]
Awesome! 😃 I'll merge this in and open up a new issue for the features we've suggested for the future. Thank you again!

**Comment by BenWeisz** [comment]
I've also removed my original extension from the marketplace and will be deleting that repo

**Comment by nagata-yoshiteru** [comment]
I released v0.0.5 in the marketplace now. Thanks!

**Comment by nagata-yoshiteru** [comment]
Hello, @BenWeisz!
I found a tiny issue when loading commented images, and fixed this bug!
Also, I already published the v0.0.6 release.
If you found any issue with this fix, please tell me!
Thanks!

**Comment by BenWeisz** [comment]
@nagata-yoshiteru Thanks you for fixing that! I'll let you know if I see any other issues

**Pull request merged**
