### PR TITLE
add defaultPreviewScale config

### PR DESCRIPTION
**Pull request by nagata-yoshiteru**
Hello, @BenWeisz !

For #14 , I added new configuration `defaultPreviewScale`.
I think there are hardly any bugs in this tiny change, but please review this PR when you have time!

Thanks!

### CODE REVIEW

**Comment by BenWeisz** [comment]
Hi @nagata-yoshiteru! I'm not sure this is the best way to handle the issue raised. The auto zoom feature would probably be easier for people to use. Although we could also keep the default zoom feature too (the default would set the default value of  below:

This is the idea I have for auto selecting the zoom size:





Here  is the actual scale that is passed to the drawing code and  is the scale that the user changes with the plus and minus buttons. 

The idea behind the  term is that it looks for the smallest amount of scaling that can be done to fit the dimensions of the image on the canvas.

The  parameter will be set by us to control the the padding around the edges of the canvas so the sides of the image are not completely touching the edges of the canvas.  would be hardcoded and chosen by us to be a value close to, but not exactly 0.

Let me know what you think! Thanks!

**Comment by nagata-yoshiteru** [comment]
Thanks, Ben!

I understand your suggestion and it looks good!
But some users want images to be displayed in a fixed scale or scales of powers of 2 ( like 25%, 50%, 100%, 200%, etc. ) to see them accurately on the screen.

So I would like to prepare 3 options for scaling as following:
1. Fixed Scale ( behave as current code )
2. Auto Scale ( behave as @BenWeisz 's suggestion )
3. Auto Scale in powers of 2 ( use the **maximum** number of powers of 2 **below** (1-\alpha)%20scale_{auto}%20scale_{auto}) )

If a user chooses the option of 3, scale_{user} is ignored and show the actual scale in the panel. So the user can control scale in actual number and view image accurately on the screen.

Let me know about my opinion too!
Thanks!

**Comment by BenWeisz** [comment]
@nagata-yoshiteru 1 and 2 make sense, but Im not sure I understand option 3 correctly. Specifically, Im not entirely sure what you mean by using the maximum number of powers below the  value?

I may have explained my equation a wrong. Basically option 2 is meant to scale by powers of 2. The scale_auto term converts the typical scale value of 1 to scale_auto, so this is like remapping the scale of 1 to scale_auto. From there, when the user clicks +/- we change do the regular multiple / divide by 2.

In any case, since these dont seem like too much work we can implement each of them and I can test it out to see what you mean :)

Sorry for any confusion and thanks for answering my questions :)

**Comment by nagata-yoshiteru** [comment]
@BenWeisz Sorry for confusing you with my poor explanation. The difference between 2 and 3 is in default scale, not the user's manipulation in +/- buttons in UI panel.

The below image shows what I want to explain.
If the user choose the option 2, the user can view an image in maximized size on the screen. But some screen piexls may have an ambiguous color if pixel boundaries of the image don't match pixel boundaries of the screen.
In contrast, if the user choose the option 3, the image will be maximized in the scale in powers of 2. In this case, pixel boundaries of the image will match pixel boundaries of the screen, and no pixel has ambiguous color.
exp

So I suggested the option 3 for those who wants images to be displayed accurately in pixels by pixels.

If you have any comments or questions, please tell me!
Thanks!

**Comment by BenWeisz** [comment]
Ahhh yes, you're completely correct. We don't want any aliasing of any sort. In that case we should not implement #2 and only do #3. Thank you for the wonderful pictures, that must have take you a while!

Excited to see how it turns out 😁

**Comment by nagata-yoshiteru** [comment]
Thanks, @BenWeisz !
I will implement the option 3 as Auto Scaling Mode when I have time, so please give me your feedback after I implement this!

Thanks!

**Comment by BenWeisz** [comment]
@nagata-yoshiteru I just tried out the new feature and it looks great! Thanks for implementing it :)

**Comment by nagata-yoshiteru** [comment]
Thank you for checking my commit, @BenWeisz !
( And sorry for forgetting to notify about it... )
I will merge this PR and release new version!

Thanks!

**Comment by BenWeisz** [comment]
Thank you!!

**Pull request merged**
